export const FETCH_ALL_TASKS_ACTION_TYPES = {
    FETCH_ALL_TASK_REQUEST: "FETCH_ALL_TASK_REQUEST",
    FETCH_ALL_TASK_FULFILLED: "FETCH_ALL_TASK_FULFILLED",
    FETCH_ALL_TASK_REJECTED: "FETCH_ALL_TASK_REJECTED",
};
export const CREATE_NEW_TASK_ACTION_TYPES = {
    CREATE_NEW_TASK_REQUEST: "CREATE_NEW_TASK_REQUEST",
    CREATE_NEW_TASK_FULFILLED: "CREATE_NEW_TASK_FULFILLED",
    CREATE_NEW_TASK_REJECTED: "CREATE_NEW_TASK_REJECTED",
};

export const DELETE_TASK_ACTION_TYPES = {
    DELETE_TASK_REQUEST: "DELETE_TASK_REQUEST",
    DELETE_TASK_FULFILLED: "DELETE_TASK_FULFILLED",
    DELETE_TASK_REJECTED: "DELETE_TASK_REJECTED",
};

export const COMPLETE_TASK_ACTION_TYPES = {
    COMPLETE_TASK_REQUEST: "COMPLETE_TASK_REQUEST",
    COMPLETE_TASK_FULFILLED: "COMPLETE_TASK_FULFILLED",
    COMPLETE_TASK_REJECTED: "COMPLETE_TASK_REJECTED",
};
export const UPDATE_TASK_ACTION_TYPES = {
    UPDATE_TASK_REQUEST: "UPDATE_TASK_REQUEST",
    UPDATE_TASK_FULFILLED: "UPDATE_TASK_FULFILLED",
    UPDATE_TASK_REJECTED: "UPDATE_TASK_REJECTED",
};